### ISSUE TITLE
Scroller doesn't stop at comparison point

### ISSUE THREAD

**Issue by senthil6789** [ryu1kn/vscode-partial-diff#23] opened 2018-02-21 06:31 UTC
Hi Team,

When I am comparing long code and copy few line to paste in the file in other tab, the comparison tab reaches to beginning of code...again I have to compare and scroll till the old selected text and then I have to continue my work.
Can you stop the scroll at same though I navigate tabs...it will be much helpful.

**Comment by ryu1kn** [comment] 2018-02-21 08:15
Hi @senthil6789 , it looks like this issue is duplicate of #22 which is raised 9 hours before? Let me know if it' is not 😉

**Closed by ryu1kn** 2018-02-21 08:15 UTC
Labels: duplicate
